variables:
  IMAGE_NAME: frontend/kanban-vue
  IMAGE_TAG: $(date '+%Y-%m-%d')
  CONTAINER_NAME: frontend-kanban-container

stages:
  - build
  - deploy

build:
  stage: build
  before_script:
    - docker login -u $REGISTRY_USER -p $REGISTRY_PASS $CI_REGISTRY
  script:
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker image tag $IMAGE_NAME:$IMAGE_TAG $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    - docker push $CI_REGISTRY/$IMAGE_NAME:$IMAGE_TAG
    - docker image rm -f $IMAGE_NAME:$IMAGE_TAG
    - docker rm -f $CONTAINER_NAME
  only:
    - master


deploy:
  stage: deploy
  script:
    - docker run -d --name $CONTAINER_NAME -p 80:80 $CI_REGISTRY_IMAGE/$IMAGE_NAME:$IMAGE_TAG
  only:
    - master
