/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarFallback: typeof import('radix-vue')['AvatarFallback']
    AvatarImage: typeof import('radix-vue')['AvatarImage']
    AvatarRoot: typeof import('radix-vue')['AvatarRoot']
    ComboboxAnchor: typeof import('radix-vue')['ComboboxAnchor']
    ComboboxContent: typeof import('radix-vue')['ComboboxContent']
    ComboboxEmpty: typeof import('radix-vue')['ComboboxEmpty']
    ComboboxGroup: typeof import('radix-vue')['ComboboxGroup']
    ComboboxInput: typeof import('radix-vue')['ComboboxInput']
    ComboboxItem: typeof import('radix-vue')['ComboboxItem']
    ComboboxItemIndicator: typeof import('radix-vue')['ComboboxItemIndicator']
    ComboboxLabel: typeof import('radix-vue')['ComboboxLabel']
    ComboboxRoot: typeof import('radix-vue')['ComboboxRoot']
    ComboboxSeparator: typeof import('radix-vue')['ComboboxSeparator']
    ComboboxViewport: typeof import('radix-vue')['ComboboxViewport']
    Header: typeof import('./src/components/molecules/Header.vue')['default']
    KanbanCard: typeof import('./src/components/molecules/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./src/components/organisms/KanbanColumn.vue')['default']
    NewTaskModal: typeof import('./src/components/molecules/NewTaskModal.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('radix-vue')['Separator']
  }
}
