/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AvatarFallback: typeof import('radix-vue')['AvatarFallback']
    AvatarImage: typeof import('radix-vue')['AvatarImage']
    AvatarRoot: typeof import('radix-vue')['AvatarRoot']
    CheckboxIndicator: typeof import('radix-vue')['CheckboxIndicator']
    CheckboxRoot: typeof import('radix-vue')['CheckboxRoot']
    ComboboxAnchor: typeof import('radix-vue')['ComboboxAnchor']
    ComboboxContent: typeof import('radix-vue')['ComboboxContent']
    ComboboxEmpty: typeof import('radix-vue')['ComboboxEmpty']
    ComboboxGroup: typeof import('radix-vue')['ComboboxGroup']
    ComboboxInput: typeof import('radix-vue')['ComboboxInput']
    ComboboxItem: typeof import('radix-vue')['ComboboxItem']
    ComboboxItemIndicator: typeof import('radix-vue')['ComboboxItemIndicator']
    ComboboxLabel: typeof import('radix-vue')['ComboboxLabel']
    ComboboxRoot: typeof import('radix-vue')['ComboboxRoot']
    ComboboxSeparator: typeof import('radix-vue')['ComboboxSeparator']
    ComboboxViewport: typeof import('radix-vue')['ComboboxViewport']
    DialogClose: typeof import('radix-vue')['DialogClose']
    DialogContent: typeof import('radix-vue')['DialogContent']
    DialogDescription: typeof import('radix-vue')['DialogDescription']
    DialogOverlay: typeof import('radix-vue')['DialogOverlay']
    DialogPortal: typeof import('radix-vue')['DialogPortal']
    DialogRoot: typeof import('radix-vue')['DialogRoot']
    DialogTitle: typeof import('radix-vue')['DialogTitle']
    DialogTrigger: typeof import('radix-vue')['DialogTrigger']
    Header: typeof import('./src/components/molecules/Header.vue')['default']
    HeaderComponent: typeof import('./src/components/molecules/HeaderComponent.vue')['default']
    KanbanCard: typeof import('./src/components/molecules/KanbanCard.vue')['default']
    KanbanColumn: typeof import('./src/components/organisms/KanbanColumn.vue')['default']
    NewTaskModal: typeof import('./src/components/molecules/NewTaskModal.vue')['default']
    ProgressIndicator: typeof import('radix-vue')['ProgressIndicator']
    ProgressRoot: typeof import('radix-vue')['ProgressRoot']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Separator: typeof import('radix-vue')['Separator']
  }
}
